"use client";
import Navigation from "@/components/Navigation";
//import type { Metadata } from 'next'
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";

//export const metadata: Metadata = {
//  title: 'Hydrogen',
//  description: 'Generated by great VPMP devs...',
//}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className="antialiased">
          <Navigation />
          <main>{children}</main>
        </body>
      </AuthProvider>
    </html>
  );
}
